version: "3.8"

services:
  # Ubuntu service with your packages
  ubuntu:
    container_name: blockbook-vanguard-container
    image: blockbook-vanguard
    build: .
    # volumes:
    #   - ./startup.sh:/app/startup.sh  # Mount your startup script
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro  # Mount cgroup for systemd
    # depends_on:
    #   - nginx
    privileged: true  # Necessary for systemd
    network_mode: host
    # ports:
    #   # - 443:19196
    #   - 18226:18226
    #   - 30312:30312
    #   - 18326:18326
    #   - 18626:18626
    #   - 19096:19096
    #   - 19196:19196
    # volumes:
    #   - ./docker_data/data:/opt/coins/data

  # Nginx service as a proxy
  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx configuration (optional)

